import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from "./components/Navbar.js"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'TFT Calculator',
  description: 'Generated by create next app ',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar suppressHydrationWarning />
        {children}
      </body>
    </html>
  )
}
